src/Entity/Votable.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Common\Collections\Selectable;

abstract class Votable {
    // these values should probably never change
    const USER_NO_VOTE = 0;
    const USER_UPVOTED = 1;
    const USER_DOWNVOTED = -1;

    const VOTE_UP = 1;
    const VOTE_DOWN = -1;
    const VOTE_RETRACT = 0;
    const VOTE_CHOICES = [self::VOTE_UP, self::VOTE_DOWN, self::VOTE_RETRACT];

    final public static function descendingNetScoreCmp(self $a, self $b): int {
        return $b->getNetScore() <=> $a->getNetScore();
    }

    /**
     * @return Vote[]|Collection|Selectable
     */
    abstract public function getVotes(): Collection;

    abstract protected function createVote(User $user, ?string $ip, int $choice): Vote;

    /**
     * @param User        $user
     * @param string|null $ip
     * @param int         $choice
     *
     * @throws \InvalidArgumentException if the vote is not a VOTE_* constant
     */
    public function vote(User $user, ?string $ip, int $choice): void {
        $vote = $this->getUserVote($user);

        if ($choice === self::VOTE_UP || $choice === self::VOTE_DOWN) {
            if ($vote) {
                $vote->setChoice($choice);
            } else {
                $this->getVotes()->add($this->createVote($user, $ip, $choice));
            }
        } elseif ($choice === self::VOTE_RETRACT) {
            $this->getVotes()->removeElement($vote);
        } else {
            throw new \InvalidArgumentException('Bad vote choice');
        }
    }

    public function getUpvotes(): int {
        $this->hydrateVoteCollection();

        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('upvote', true));

        return count($this->getVotes()->matching($criteria));
    }

    public function getDownvotes(): int {
        $this->hydrateVoteCollection();

        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('upvote', false));

        return count($this->getVotes()->matching($criteria));
    }

    public function getNetScore(): int {
        return $this->getUpvotes() - $this->getDownvotes();
    }

    public function getUserChoice(User $user): int {
        $vote = $this->getUserVote($user);

        if (!$vote) {
            return self::USER_NO_VOTE;
        }

        return $vote->getChoice();
    }

    private function getUserVote(User $user): ?Vote {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('user', $user));

        return $this->getVotes()->matching($criteria)->first() ?: null;
    }

    /**
     * Hydrates the vote collection. This performs essentially the same task as
     * setting the fetch mode to EAGER, but makes it easier to deal with cases
     * where you don't want eager fetching, as you don't have to go around
     * setting the fetch mode manually (which I couldn't even do successfully).
     *
     * For the purpose of counting the net score and such, fetching the entire
     * collection in advance speeds up things considerably when there are
     * multiple entities.
     */
    private function hydrateVoteCollection(): void {
        $this->getVotes()->get(-1);
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Form\EventListener\PasswordEncodingSubscriber;
use App\Form\Model\UserData;
use App\Form\Type\HoneypotType;
use Gregwar\CaptchaBundle\Type\CaptchaType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

final class UserType extends AbstractType {
    /**
     * @var UserPasswordEncoderInterface
     */
    private $encoder;

    /**
     * @var AuthorizationCheckerInterface
     */
    private $authorizationChecker;

    /**
     * @param UserPasswordEncoderInterface  $encoder
     * @param AuthorizationCheckerInterface $authorizationChecker
     */
    public function __construct(
        UserPasswordEncoderInterface $encoder,
        AuthorizationCheckerInterface $authorizationChecker
    ) {
        $this->encoder = $encoder;
        $this->authorizationChecker = $authorizationChecker;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {
        if ($options['honeypot']) {
            $builder->add('phone', HoneypotType::class);
        }

        $editing = $builder->getData() && $builder->getData()->getEntityId();

        $builder
            ->add('username', TextType::class, [
                'help' => 'user.username_rules',
            ])
            ->add('password', RepeatedType::class, [
                'help' => 'user.password_rules',
                'property_path' => 'plainPassword',
                'required' => !$editing,
                'first_options' => ['label' => $editing ? 'user_form.new_password' : 'user_form.password'],
                'second_options' => ['label' => $editing ? 'user_form.repeat_new_password' : 'user_form.repeat_password'],
                'type' => PasswordType::class,
            ])
            ->add('email', EmailType::class, [
                'help' => 'user.email_optional',
                'required' => false,
            ]);

        if (!$editing) {
            $builder->add('verification', CaptchaType::class, [
                'as_url' => true,
                'reload' => true,
            ]);
        }

        $builder->add('submit', SubmitType::class, [
            'label' => 'user_form.'.($editing ? 'save' : 'register'),
        ]);

        $builder->addEventSubscriber(new PasswordEncodingSubscriber($this->encoder));
    }

    public function finishView(FormView $view, FormInterface $form, array $options) {
        if ($form->getData() && $form->getData()->getEntityId()) {
            // don't auto-complete the password fields when editing the user
            $view['password']['first']->vars['attr']['autocomplete'] = 'new-password';
            $view['password']['second']->vars['attr']['autocomplete'] = 'new-password';
        }
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => UserData::class,
            'honeypot' => true,
            'label_format' => 'user_form.%name%',
            'validation_groups' => function (FormInterface $form) {
                if ($form->getData()->getEntityId() !== null) {
                    $groups[] = 'edit';
                } else {
                    $groups[] = 'registration';
                }

                return $groups;
            },
        ]);

        $resolver->setAllowedTypes('honeypot', ['bool']);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Forum;
use App\Entity\Submission;
use App\Entity\User;
use App\Entity\UserBlock;
use App\Form\ConfirmDeletionType;
use App\Form\Model\UserBlockData;
use App\Form\Model\UserData;
use App\Form\Model\UserFilterData;
use App\Form\UserBiographyType;
use App\Form\UserBlockType;
use App\Form\UserFilterType;
use App\Form\UserSettingsType;
use App\Form\UserType;
use App\Message\DeleteUser;
use App\Repository\CommentRepository;
use App\Repository\ForumBanRepository;
use App\Repository\NotificationRepository;
use App\SubmissionFinder\Criteria;
use App\SubmissionFinder\SubmissionFinder;
use App\Repository\UserRepository;
use App\Security\AuthenticationHelper;
use Doctrine\Common\Persistence\ObjectManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

/**
 * @Entity("user", expr="repository.findOneOrRedirectToCanonical(username, 'username')")
 */
final class UserController extends AbstractController {
    /**
     * @var SubmissionFinder
     */
    private $submissionFinder;

    /**
     * @var CommentRepository
     */
    private $comments;

    /**
     * @var string
     */
    private $defaultLocale;

    public function __construct(
        SubmissionFinder $submissionFinder,
        CommentRepository $comments,
        string $defaultLocale
    ) {
        $this->submissionFinder = $submissionFinder;
        $this->comments = $comments;
        $this->defaultLocale = $defaultLocale;
    }

    /**
     * Show the user's profile page.
     *
     * @param User           $user
     * @param Request        $request
     * @param UserRepository $users
     *
     * @return Response
     */
    public function userPage(User $user, Request $request, UserRepository $users) {
        $nextUnixTime = $request->query->getInt('next_timestamp');

        if ($nextUnixTime) {
            $nextTimestamp = new \DateTime('@'.$nextUnixTime);
        }

        $contributions = $users->findContributions($user);

        if ($nextUnixTime && !\count($contributions)) {
            throw $this->createNotFoundException('No such page');
        }

        return $this->render('user/user.html.twig', [
            'contributions' => $contributions,
            'user' => $user,
        ]);
    }

    public function submissions(User $user): Response {
        $criteria = (new Criteria(Submission::SORT_NEW))
            ->showUsers($user);

        $submissions = $this->submissionFinder->find($criteria);

        return $this->render('user/submissions.html.twig', [
            'submissions' => $submissions,
            'user' => $user,
        ]);
    }

    public function comments(User $user, int $page): Response {
        $comments = $user->getPaginatedComments($page);

        $this->comments->hydrate(...$comments);

        return $this->render('user/comments.html.twig', [
            'comments' => $comments,
            'user' => $user,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("ROLE_ADMIN", statusCode=403)
     *
     * @param UserRepository $users
     * @param int            $page
     * @param Request        $request
     *
     * @return Response
     */
    public function list(UserRepository $users, int $page, Request $request) {
        $filter = new UserFilterData();
        $criteria = $filter->buildCriteria();

        $form = $this->createForm(UserFilterType::class, $filter);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $criteria = $filter->buildCriteria();
        }

        return $this->render('user/list.html.twig', [
            'form' => $form->createView(),
            'page' => $page,
            'users' => $users->findPaginated($page, $criteria),
        ]);
    }

    public function registration(
        Request $request,
        ObjectManager $em,
        AuthenticationHelper $authenticationHelper
    ) {
        if ($this->isGranted('ROLE_USER')) {
            return $this->redirectToRoute('front');
        }

        $data = new UserData();
        $data->setLocale($request->getLocale());

        $form = $this->createForm(UserType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $data->toUser();

            $em->persist($user);
            $em->flush();

            $response = $this->redirectToRoute('front');

            $authenticationHelper->login($user, $request, $response, 'main');

            $this->addFlash('success', 'flash.user_account_registered');

            return $response;
        }

        return $this->render('user/registration.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @IsGranted("edit_user", subject="user", statusCode=403)
     *
     * @param ObjectManager $em
     * @param User          $user
     * @param Request       $request
     *
     * @return Response
     */
    public function editUser(ObjectManager $em, User $user, Request $request) {
        $data = UserData::fromUser($user);

        $form = $this->createForm(UserType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data->updateUser($user);

            $em->flush();

            $this->addFlash('success', 'flash.user_settings_updated');

            return $this->redirectToRoute('edit_user', [
                'username' => $user->getUsername(),
            ]);
        }

        return $this->render('user/edit.html.twig', [
            'form' => $form->createView(),
            'user' => $user,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @IsGranted("edit_user", subject="user", statusCode=403)
     */
    public function deleteAccount(User $user, Request $request, TokenStorageInterface $tokenStorage): Response {
        $form = $this->createForm(ConfirmDeletionType::class, null, [
            'name' => $user->getUsername(),
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($user === $this->getUser()) {
                $tokenStorage->setToken(null);
            }

            $this->dispatchMessage(new DeleteUser($user));

            $this->addFlash('notice', 'flash.account_deletion_in_progress');

            return $this->redirectToRoute('front');
        }

        return $this->render('user/delete_account.html.twig', [
            'form' => $form->createView(),
            'user' => $user,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("edit_user", subject="user", statusCode=403)
     *
     * @param ObjectManager $em
     * @param User          $user
     * @param Request       $request
     *
     * @return Response
     */
    public function userSettings(ObjectManager $em, User $user, Request $request) {
        $data = UserData::fromUser($user);

        $form = $this->createForm(UserSettingsType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data->updateUser($user);

            $em->flush();

            $this->addFlash('success', 'flash.user_settings_updated');

            return $this->redirect($request->getUri());
        }

        return $this->render('user/settings.html.twig', [
            'form' => $form->createView(),
            'user' => $user,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("edit_user", subject="user", statusCode=403)
     *
     * @param ObjectManager $em
     * @param User          $user
     * @param Request       $request
     *
     * @return Response
     */
    public function editBiography(ObjectManager $em, User $user, Request $request) {
        $data = UserData::fromUser($user);

        $form = $this->createForm(UserBiographyType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data->updateUser($user);

            $em->flush();

            $this->addFlash('success', 'flash.user_biography_updated');

            return $this->redirect($request->getUri());
        }

        return $this->render('user/edit_biography.html.twig', [
            'form' => $form->createView(),
            'user' => $user,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("edit_user", subject="user", statusCode=403)
     *
     * @param User $user
     * @param int $page
     *
     * @return Response
     */
    public function blockList(User $user, int $page) {
        return $this->render('user/block_list.html.twig', [
            'blocks' => $user->getPaginatedBlocks($page),
            'user' => $user,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Entity("blockee", expr="repository.findOneOrRedirectToCanonical(username, 'username')")
     *
     * @param User          $blockee
     * @param Request       $request
     * @param ObjectManager $em
     *
     * @return Response
     */
    public function block(User $blockee, Request $request, ObjectManager $em) {
        /* @var User $blocker */
        $blocker = $this->getUser();

        if ($blocker->isBlocking($blockee)) {
            throw $this->createNotFoundException('The user is already blocked');
        }

        $data = new UserBlockData();

        $form = $this->createForm(UserBlockType::class, $data);
        $form->handleRequest($request);

templates/user/_macros.html.twig
{##
 # TODO: remove this, it blows
 # - flag (int|string): one of App\Entity\UserFlags constants, or 'admin'/'moderator'
 # - class (string): Additional classes
 #}
{%- macro user_link(user, options) -%}
  {%- from _self import user_flag -%}
  <a href="{{ path('user', { username: user.username }) }}" class="{{ options.class ?? '' }}">
    {{- (options.prefix ?? false) ? '/u/' -}}
    {{- user.username -}}
  </a>
  {{ user_flag(options.flag ?? 0) }}
{%- endmacro user_link -%}

{% macro user_flag(flag) %}
  {%- if flag is same as(0) -%}
  {%- elseif flag is constant('App\\Entity\\UserFlags::FLAG_ADMIN') or flag == 'admin' -%}
    <small class="fg-red text-sm user-flag ">{{ 'user_flag.admin'|trans }}</small>
  {%- elseif flag is constant('App\\Entity\\UserFlags::FLAG_MODERATOR') or flag == 'moderator' -%}
    <small class="fg-green text-sm user-flag">{{ 'user_flag.moderator'|trans }}</small>
  {%- endif -%}
{% endmacro user_flag %}

templates/user/_nav.html.twig
<nav class="user-nav">
  <ul class="unlistify nav">
    {% for tab in [
      { path: 'user', label: 'label.overview' },
      { path: 'user_submissions', label: 'user.submissions' },
      { path: 'user_comments', label: 'user.comments' },
    ] %}
      <li>
        <a href="{{ path(tab.path, {username: user.username}) }}"
           class="tab {{ tab.path == current ? 'tab--active' }}">
          {{- tab.label|trans -}}
        </a>
      </li>
    {% endfor %}
  </ul>
</nav>

<h1 class="page-heading break-text no-desktop">{{ user.username }}</h1>

templates/user/base.html.twig
{% extends 'base.html.twig' %}

{% block site_nav_active app.user is same as(user) ? 'user' %}
{% block user_toolbox_active app.request.attributes.get('_route') %}

{% block sidebar %}
  {% from '_macros/time.html.twig' import relative_time %}

  <section class="sidebar__section sidebar-card">
    <h1 class="sidebar__title no-margin break-text">
      <a href="{{ path('user', {username: user.username}) }}" class="user-bio__user-link">{{ user.username }}</a>
    </h1>

    <p>
      <small class="fg-muted text-md">{{ 'user.registered'|trans({
        '%timestamp%': relative_time(user.created, { time_format: 'none', natural: true })
      })|raw }}
      </small>
    </p>

    {% if user.biography is not empty %}
      <div class="user-bio__biography">{{ user.biography|cached_markdown({ context: 'user_biography', user: user })|raw }}</div>
    {% endif %}
  </section>

  {% set active_ban = user.activeBan %}

  {% if is_granted('ROLE_ADMIN') and active_ban %}
    <section class="sidebar__section sidebar-card bg-red">
      <h1 class="sidebar__title">{{ 'heading.this_user_is_banned'|trans }}</h1>

      <dl class="table-list">
        <dt>{{ 'label.reason'|trans }}</dt>
        <dd>{{ active_ban.reason }}</dd>

        <dt>{{ 'label.banned_by'|trans }}</dt>
        <dd>
          <a href="{{ path('user', { username: active_ban.bannedBy.username }) }}">
            {{- active_ban.bannedBy.username -}}
          </a>
        </dd>

        <dt>{{ 'label.expires'|trans }}</dt>
        <dd>
          {%- if active_ban.expiresAt -%}
            {{ relative_time(active_ban.expiresAt) }}
          {%- else -%}
            <small class="fg-muted text-md">{{ 'label.never'|trans }}</small>
          {%- endif -%}
        </dd>
      </dl>

      <p>
        <a href="{{ path('unban_user', { username: user.username }) }}"
           class="button">
          {{- 'action.unban'|trans -}}
        </a>
      </p>
    </section>
  {% endif %}

  {% set toolbox_items = {
    ('user.message'|trans): {
      route: 'compose_message',
      condition: is_granted('ROLE_USER') and user is not same as(app.user) and is_granted('message', user),
    },
    ('nav.block_user'|trans): {
      route: 'block_user',
      condition: is_granted('ROLE_USER') and user is not same as(app.user) and not app.user.isBlocking(user),
    },
    ('action.ban'|trans): {
      route: 'ban_user',
      condition: is_granted('ROLE_ADMIN') and user is not same as(app.user) and not active_ban,
    },
    ('nav.forum_bans'|trans): {
      route: 'user_forum_bans',
      condition: is_granted('ROLE_ADMIN')
    },
    ('nav.edit_biography'|trans): {
      route: 'edit_biography',
      condition: is_granted('ROLE_USER') and user is same as(app.user)
    },
    ('nav.hidden_forums'|trans): {
      route: 'hidden_forums',
      condition: is_granted('ROLE_USER') and user is same as(app.user)
    }
  } %}

  {% set open = false %}
  {% for label in toolbox_items|keys|sort|filter(label => toolbox_items[label].condition) %}
    {% if loop.first %}
      {% set open = true %}
      <section class="sidebar__section sidebar-card">
        <h1 class="sidebar__title">{{ 'label.toolbox'|trans }}</h1>
        <ul class="no-margin unlistify sidebar__no-padding">
    {% endif %}
    {% set item = toolbox_items[label] %}
    <li>
      <a href="{{ path(item.route, { username: user.username }) }}"
         class="menu-item {{ block('user_toolbox_active') == item.route ? 'menu-item--active' }}">
        {{- label -}}
      </a>
    </li>
  {% endfor %}
  {% if open %}
        </ul>
      </section>
  {% endif %}

  {% if is_granted('ROLE_ADMIN') %}
    <section class="sidebar__section sidebar-card">
      <h1 class="sidebar__title">{{ 'heading.user_roles'|trans }}</h1>
      <form action="{{ path(user.trusted ? 'mark_user_untrusted' : 'mark_user_trusted', {username: user.username}) }}" method="post" class="form">
        <input type="hidden" name="token" value="{{ csrf_token('mark_trusted') }}">
        <div class="form__row">
          <button class="button button--secondary">{{ (not user.trusted ? 'action.mark_as_trusted' : 'action.mark_as_untrusted')|trans }}</button>
        </div>
      </form>
    </section>
  {% endif %}

  {% if user.moderatorTokens|length > 0 %}
    <section class="sidebar__section sidebar-card">
      <h1 class="sidebar__title break-text">{{ 'user.moderates'|trans({'%username%': user.username}) }}</h1>

      <ul class="unlistify nav nav--guttered nav--slim-gutters">
        {% for token in user.moderatorTokens %}
          <li>
            <a href="{{ path('forum', {forum_name: token.forum.name}) }}"
               class="button button--secondary button--small">
              {{- token.forum.name -}}
            </a>
          </li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}
{% endblock %}

templates/user/block.html.twig
{% extends 'user/base.html.twig' %}
{% from 'user/_macros.html.twig' import user_link %}

{% block title 'title.blocking_user'|trans({'%user%': '/u/'~user.username}) %}

{% block body %}
  <h1 class="page-heading">
    {{ 'title.blocking_user'|trans({
      '%user%': user_link(user, {prefix: true}),
    })|raw }}
  </h1>

  {% embed '_layouts/alert.html.twig' with { type: 'info' } %}
    {% block alert_text %}
      <p>{{ 'help.block_users'|trans }}</p>
    {% endblock alert_text %}
  {% endembed %}

  {{ form(form) }}
{% endblock %}

templates/user/delete_account.html.twig
{% extends 'user/base.html.twig' %}

{% block title 'title.delete_account'|trans %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  <p>{{ 'delete_account.lead'|trans }}</p>

  <ul>
    <li>{{ 'delete_account.submissions'|trans }}</li>
    <li>{{ 'delete_account.comments'|trans }}</li>
    <li>{{ 'delete_account.messages'|trans }}</li>
    <li>{{ 'delete_account.votes'|trans }}</li>
    <li>{{ 'delete_account.metadata'|trans }}</li>
  </ul>

  {% embed '_layouts/alert.html.twig' with { type: 'warn' } %}
    {% block alert_paragraph app.user is same as(user)
      ? 'flash.delete_account_warning'|trans
      : '<strong class="text-xl">%s</strong>'|format('flash.delete_someone_elses_account_warning'|trans|e)|raw %}
  {% endembed %}

  {{ form_start(form) }}
    {{ form_row(form.name, { label: 'label.confirm_username'|trans }) }}

    {{ form_row(form.confirm, { label: 'label.delete_account_confirmation'|trans }) }}

    <div class="form__row form__button-row">
      <button type="submit" class="button">{{ 'action.delete_account'|trans }}</button>
    </div>
  {{ form_end(form) }}
{% endblock body %}

templates/user/edit.html.twig
{% extends 'user/base.html.twig' %}
{% from '_macros/icon.html.twig' import icon %}

{% block title 'edit_user.title'|trans({'%username%': user.username}) %}

{% block site_nav_user_menu_active 'account' %}

{% block body %}
  <h1 class="page-heading break-text">{{ block('title') }}</h1>

  {% if app.user != user %}
    {% embed '_layouts/alert.html.twig' with { type: 'warn' } %}
      {% block alert_paragraph 'flash.editing_credentials_of_other_user'|trans %}
    {% endembed %}
  {% endif %}

  <fieldset class="fieldset">
    <legend>{{ 'heading.credentials'|trans }}</legend>

    {{ include('user/_form.html.twig', { form: form }, with_context=false) }}
  </fieldset>

  <fieldset class="fieldset">
    <legend>{{ 'heading.delete_account'|trans }}</legend>

    <p class="no-margin">
      <a href="{{ path('delete_account', { username: user.username }) }}"
         class="button button--secondary">
        {{- 'nav.delete_this_account'|trans -}}
      </a>
    </p>
  </fieldset>
{% endblock %}

templates/user/edit_biography.html.twig
{% extends 'user/base.html.twig' %}

{% block title 'title.editing_biography_for_user'|trans({'%user%': user.username}) %}

{% block body %}
  <h1>
    {{ 'title.editing_biography_for_user'|trans({
      '%user%': '<a href="%s">/u/%s</a>'|format(path('user', {username: user.username})|e, user.username|e)
    })|raw }}
  </h1>

  {{ form_start(form) }}
    {{ form_row(form.biography, {attr: {rows: 5}}) }}

    {{ form_row(form.save) }}
  {{ form_end(form) }}
{% endblock %}

templates/user/registration.html.twig
{% extends 'base.html.twig' %}

{% block site_nav_active 'registration' %}
{% block title 'title.sign_up'|trans %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  {% include 'user/_form.html.twig' %}
{% endblock %}

templates/user/submissions.html.twig
{% extends 'user/base.html.twig' %}
{% from 'submission/_macros.html.twig' import submission %}

{% block head %}
  <link rel="canonical" href="{{ url('user_submissions', {username: user.username}) }}">
  {{ include('_includes/meta_pagination.html.twig', {pager: submissions}) }}
{% endblock %}

{% block site_nav_user_menu_active 'profile' %}

{% block title 'user.submissions'|trans %}

{% block body %}
  {{ include('user/_nav.html.twig', {current: 'user_submissions', user: user}, with_context=false) }}

  {% for submission in submissions %}
    {{ submission(submission) }}
  {% else %}
    <p class="no-entries">
      <small class="fg-muted text-md">{{ 'flash.no_entries_to_display'|trans }}</small>
    </p>
  {% endfor %}

  {{ include('_includes/pagination.html.twig', {pager: submissions}, with_context=false) }}
{% endblock %}